<?php
/**
 * Import quiz data from PDF file
 * Extracts embedded CSV data from PDFs generated by our system.
 *
 * Supported embedding methods (tried in order):
 *   1. XMP Metadata  — <quiz:data>base64...</quiz:data>
 *   2. PDF comments  — % QUIZ_CSV_DATA_START … % QUIZ_CSV_DATA_END
 *   3. Legacy marker — QUIZ_DATA_START:base64:QUIZ_DATA_END
 *   4. Fallback      — decompress PDF streams and search for comment markers
 */

function importQuizFromPdf(string $filepath): array
{
    if (!file_exists($filepath)) {
        return ['success' => false, 'error' => 'File not found.'];
    }

    $content = file_get_contents($filepath);
    if ($content === false) {
        return ['success' => false, 'error' => 'Could not read PDF file.'];
    }

    $csvData = null;

    // ── METHOD 1: XMP Metadata (<quiz:data> tag) ──────────────────────────────
    if (preg_match('/<quiz:data>([A-Za-z0-9+\/=\s]+)<\/quiz:data>/s', $content, $matches)) {
        $base64Data = preg_replace('/\s+/', '', $matches[1]);
        $decoded    = base64_decode($base64Data, true);
        if ($decoded !== false && !empty($decoded)) {
            $csvData = $decoded;
        }
    }

    // ── METHOD 2: PDF comment block (% QUIZ_CSV_DATA_START … END) ────────────
    if ($csvData === null) {
        $csvData = _extractFromCommentBlock($content);
    }

    // ── METHOD 3: Legacy inline marker (QUIZ_DATA_START:base64:QUIZ_DATA_END) ─
    if ($csvData === null &&
        preg_match('/QUIZ_DATA_START:([A-Za-z0-9+\/=\r\n]+):QUIZ_DATA_END/', $content, $matches)) {
        $base64Data = preg_replace('/\s+/', '', $matches[1]);
        $decoded    = base64_decode($base64Data, true);
        if ($decoded !== false && !empty($decoded)) {
            $csvData = $decoded;
        }
    }

    // ── METHOD 4: Decompress PDF streams and retry ────────────────────────────
    if ($csvData === null) {
        $text = '';
        if (preg_match_all('/stream\s*[\r\n]+(.*?)[\r\n]+endstream/s', $content, $streamMatches)) {
            foreach ($streamMatches[1] as $stream) {
                $decoded = @gzuncompress($stream);
                $text   .= ($decoded !== false ? $decoded : $stream) . "\n";
            }
        }
        // Also grab plain text objects
        if (preg_match_all('/\(((?:[^()\\\\]|\\\\.)*)\)\s*Tj/s', $content, $textMatches)) {
            foreach ($textMatches[1] as $t) {
                $t     = str_replace(['\\(', '\\)', '\\\\'], ['(', ')', '\\'], $t);
                $text .= $t . "\n";
            }
        }
        if (!empty($text)) {
            $csvData = _extractFromCommentBlock($text);
        }
    }

    // ── Parse extracted CSV data ──────────────────────────────────────────────
    if ($csvData !== null && trim($csvData) !== '') {
        $result = _parseCsvData($csvData);
        if (!empty($result)) {
            return ['success' => true, 'data' => $result];
        }
    }

    return [
        'success' => false,
        'error'   => 'Could not extract quiz data from this PDF. '
                   . 'This PDF may not have been generated by our system, or the embedded data may be corrupted. '
                   . 'Please download a fresh template and try again.',
    ];
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Look for % QUIZ_CSV_DATA_START … % QUIZ_CSV_DATA_END comment block
 * and reassemble the base64 payload.
 */
function _extractFromCommentBlock(string $text): ?string
{
    if (!preg_match('/%\s*QUIZ_CSV_DATA_START\s*[\r\n]+(.*?)%\s*QUIZ_CSV_DATA_END/s', $text, $matches)) {
        return null;
    }

    $lines      = explode("\n", $matches[1]);
    $base64Parts = [];

    foreach ($lines as $line) {
        if (preg_match('/^%\s*([A-Za-z0-9+\/=]+)\s*$/', trim($line), $lineMatch)) {
            $base64Parts[] = $lineMatch[1];
        }
    }

    if (empty($base64Parts)) {
        return null;
    }

    $decoded = base64_decode(implode('', $base64Parts), true);
    return ($decoded !== false && !empty($decoded)) ? $decoded : null;
}

/**
 * Parse a CSV string into an array of data rows.
 *
 * FIX: The original code had a logic bug where the `continue` statement
 * fired on the same iteration that set $headerFound = true, causing the
 * first real data row to be silently skipped.
 *
 * Correct flow:
 *   - Scan lines until we find the header (contains "subject_name").
 *   - Once found, mark it and move on — do NOT skip the next line.
 *   - All subsequent non-empty, non-comment lines are data rows.
 */
function _parseCsvData(string $csvData): array
{
    $lines       = explode("\n", $csvData);
    $data        = [];
    $headerFound = false;

    foreach ($lines as $line) {
        $line = trim($line);

        if ($line === '') {
            continue;
        }

        // Skip comment / hint lines
        if (strpos($line, '# HINT') !== false || strpos($line, '#') === 0) {
            continue;
        }

        // Look for the header row
        if (!$headerFound) {
            if (stripos($line, 'subject_name') !== false) {
                $headerFound = true;
                // Header row itself is skipped — continue to next line
            }
            // Whether we just found the header or not, skip this line
            continue;
        }

        // Parse data row
        $row = str_getcsv($line);

        if (count($row) < 9) {
            continue;
        }

        // Skip completely empty rows
        $hasContent = false;
        foreach ($row as $cell) {
            if (trim($cell) !== '') {
                $hasContent = true;
                break;
            }
        }
        if (!$hasContent) {
            continue;
        }

        // Skip sample/hint rows
        $firstCell = strtolower(trim($row[0]));
        if (strpos($firstCell, 'e.g') !== false || strpos($firstCell, 'pick') !== false) {
            continue;
        }

        // Skip rows where the question column (index 3) is empty
        if (trim($row[3]) === '') {
            continue;
        }

        $data[] = $row;
    }

    return $data;
}
