<?php
/**
 * Import quiz data from PDF file
 * Extracts embedded data from PDFs generated by our system
 * Supports both XMP metadata and PDF comment-based data storage
 */

function importQuizFromPdf(string $filepath): array
{
    if (!file_exists($filepath)) {
        return ['success' => false, 'error' => 'File not found.'];
    }

    // Read PDF content as binary
    $content = file_get_contents($filepath);
    
    if ($content === false) {
        return ['success' => false, 'error' => 'Could not read PDF file.'];
    }

    $csvData = null;

    // METHOD 1: Extract from XMP Metadata (quiz:data tag)
    if (preg_match('/<quiz:data>([A-Za-z0-9+\/=\s]+)<\/quiz:data>/s', $content, $matches)) {
        $base64Data = preg_replace('/\s+/', '', $matches[1]);
        $csvData = base64_decode($base64Data);
    }

    // METHOD 2: Extract from PDF comments (% QUIZ_CSV_DATA_START ... % QUIZ_CSV_DATA_END)
    if (!$csvData && preg_match('/%\s*QUIZ_CSV_DATA_START\s*\n(.*?)%\s*QUIZ_CSV_DATA_END/s', $content, $matches)) {
        // Extract all comment lines between markers
        $commentBlock = $matches[1];
        $lines = explode("\n", $commentBlock);
        $base64Parts = [];
        
        foreach ($lines as $line) {
            // Extract data after % comment marker
            if (preg_match('/^%\s*([A-Za-z0-9+\/=]+)\s*$/', $line, $lineMatch)) {
                $base64Parts[] = $lineMatch[1];
            }
        }
        
        if (!empty($base64Parts)) {
            $base64Data = implode('', $base64Parts);
            $csvData = base64_decode($base64Data);
        }
    }

    // METHOD 3: Look for old-style embedded data marker (QUIZ_DATA_START:base64:QUIZ_DATA_END)
    if (!$csvData && preg_match('/QUIZ_DATA_START:([A-Za-z0-9+\/=\r\n]+):QUIZ_DATA_END/', $content, $matches)) {
        $base64Data = preg_replace('/\s+/', '', $matches[1]);
        $csvData = base64_decode($base64Data);
    }

    // If we successfully extracted CSV data, parse it
    if ($csvData && !empty($csvData)) {
        $lines = explode("\n", $csvData);
        $data = [];
        $headerFound = false;
        
        foreach ($lines as $line) {
            $line = trim($line);
            
            if (empty($line)) continue;
            
            // Skip header row
            if (!$headerFound) {
                if (stripos($line, 'subject_name') !== false) {
                    $headerFound = true;
                }
                continue;
            }
            
            // Skip hint/comment rows
            if (strpos($line, '# HINT') !== false || strpos($line, '#') === 0) {
                continue;
            }
            
            // Parse CSV row
            $row = str_getcsv($line);
            if (count($row) >= 9) {
                // Skip completely empty rows
                $hasContent = false;
                foreach ($row as $cell) {
                    if (!empty(trim($cell))) {
                        $hasContent = true;
                        break;
                    }
                }
                
                if ($hasContent) {
                    $data[] = $row;
                }
            }
        }
        
        if (!empty($data)) {
            return ['success' => true, 'data' => $data];
        }
    }

    // FALLBACK: Try to extract text from PDF streams
    $text = '';
    
    // Extract from stream objects
    if (preg_match_all('/stream\s*[\r\n]+(.*?)[\r\n]+endstream/s', $content, $matches)) {
        foreach ($matches[1] as $stream) {
            // Try decompression
            $decoded = @gzuncompress($stream);
            if ($decoded !== false) {
                $text .= $decoded . "\n";
            } else {
                $text .= $stream . "\n";
            }
        }
    }
    
    // Extract text objects (between parentheses)
    if (preg_match_all('/\(((?:[^()\\\\]|\\\\.)*)?\)\s*Tj/s', $content, $matches)) {
        foreach ($matches[1] as $textMatch) {
            // Unescape PDF text
            $textMatch = str_replace(['\\(', '\\)', '\\\\'], ['(', ')', '\\'], $textMatch);
            $text .= $textMatch . "\n";
        }
    }
    
    // Try to find data in extracted text
    if (preg_match('/%\s*QUIZ_CSV_DATA_START\s*\n(.*?)%\s*QUIZ_CSV_DATA_END/s', $text, $matches)) {
        $commentBlock = $matches[1];
        $lines = explode("\n", $commentBlock);
        $base64Parts = [];
        
        foreach ($lines as $line) {
            if (preg_match('/^%\s*([A-Za-z0-9+\/=]+)\s*$/', $line, $lineMatch)) {
                $base64Parts[] = $lineMatch[1];
            }
        }
        
        if (!empty($base64Parts)) {
            $base64Data = implode('', $base64Parts);
            $csvData = base64_decode($base64Data);
            
            if ($csvData && !empty($csvData)) {
                $lines = explode("\n", $csvData);
                $data = [];
                $headerFound = false;
                
                foreach ($lines as $line) {
                    $line = trim($line);
                    if (empty($line)) continue;
                    
                    if (!$headerFound) {
                        if (stripos($line, 'subject_name') !== false) {
                            $headerFound = true;
                        }
                        continue;
                    }
                    
                    if (strpos($line, '# HINT') !== false || strpos($line, '#') === 0) {
                        continue;
                    }
                    
                    $row = str_getcsv($line);
                    if (count($row) >= 9) {
                        $hasContent = false;
                        foreach ($row as $cell) {
                            if (!empty(trim($cell))) {
                                $hasContent = true;
                                break;
                            }
                        }
                        
                        if ($hasContent) {
                            $data[] = $row;
                        }
                    }
                }
                
                if (!empty($data)) {
                    return ['success' => true, 'data' => $data];
                }
            }
        }
    }
    
    // No data found
    return [
        'success' => false, 
        'error' => 'Could not extract quiz data from this PDF. This PDF may not have been generated by our system, or the data may have been corrupted. Please download a fresh template and try again.'
    ];
}
